/*
 * Copyright 2010 The Rabbit Eclipse Plug-in Project
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2010.02.07 at 11:04:55 AM NZDT
//

package rabbit.data.internal.xml.schema.resources;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the rabbit.tracking.storage.xml.resourceschema
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _Resources_QNAME = new QName("", "resources");

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package:
   * rabbit.tracking.storage.xml.resourceschema
   * 
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link ResourceListType }
   * 
   */
  public ResourceListType createResourceListType() {
    return new ResourceListType();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <} {@link ResourceListType }
   * {@code >}
   * 
   */
  @XmlElementDecl(namespace = "", name = "resources")
  public JAXBElement<ResourceListType> createResources(ResourceListType value) {
    return new JAXBElement<ResourceListType>(_Resources_QNAME,
        ResourceListType.class, null, value);
  }

  /**
   * Create an instance of {@link ResourceType }
   * 
   */
  public ResourceType createResourceType() {
    return new ResourceType();
  }

}
