/*
 * Copyright 2010 The Rabbit Eclipse Plug-in Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.28 at 03:18:14 PM NZDT 
//


package rabbit.core.internal.storage.xml.schema.events;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for launchEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="launchEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{}durationEventType">
 *       &lt;sequence>
 *         &lt;element name="fileId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="launchName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="launchTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="launchMode" use="required" type="{}launchMode" />
 *       &lt;attribute name="launchType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "launchEventType", propOrder = {
    "fileId"
})
public class LaunchEventType
    extends DurationEventType
{

    protected List<String> fileId;
    @XmlAttribute(required = true)
    protected String launchName;
    @XmlAttribute(required = true)
    protected XMLGregorianCalendar launchTime;
    @XmlAttribute(required = true)
    protected LaunchMode launchMode;
    @XmlAttribute
    protected String launchType;

    /**
     * Gets the value of the fileId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFileId() {
        if (fileId == null) {
            fileId = new ArrayList<String>();
        }
        return this.fileId;
    }

    /**
     * Gets the value of the launchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaunchName() {
        return launchName;
    }

    /**
     * Sets the value of the launchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaunchName(String value) {
        this.launchName = value;
    }

    /**
     * Gets the value of the launchTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLaunchTime() {
        return launchTime;
    }

    /**
     * Sets the value of the launchTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLaunchTime(XMLGregorianCalendar value) {
        this.launchTime = value;
    }

    /**
     * Gets the value of the launchMode property.
     * 
     * @return
     *     possible object is
     *     {@link LaunchMode }
     *     
     */
    public LaunchMode getLaunchMode() {
        return launchMode;
    }

    /**
     * Sets the value of the launchMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaunchMode }
     *     
     */
    public void setLaunchMode(LaunchMode value) {
        this.launchMode = value;
    }

    /**
     * Gets the value of the launchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaunchType() {
        return launchType;
    }

    /**
     * Sets the value of the launchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaunchType(String value) {
        this.launchType = value;
    }

}
