//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.02 at 08:08:02 PM NZDT 
//


package rabbit.tracking.storage.xml.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eventListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commandEvents" type="{}commandEventListType" maxOccurs="unbounded"/>
 *         &lt;element name="workbenchEvents" type="{}workbenchEventListType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventListType", propOrder = {
    "commandEvents",
    "workbenchEvents"
})
public class EventListType {

    @XmlElement(required = true)
    protected List<CommandEventListType> commandEvents;
    @XmlElement(required = true)
    protected List<WorkbenchEventListType> workbenchEvents;

    /**
     * Gets the value of the commandEvents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commandEvents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommandEvents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommandEventListType }
     * 
     * 
     */
    public List<CommandEventListType> getCommandEvents() {
        if (commandEvents == null) {
            commandEvents = new ArrayList<CommandEventListType>();
        }
        return this.commandEvents;
    }

    /**
     * Gets the value of the workbenchEvents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workbenchEvents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkbenchEvents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkbenchEventListType }
     * 
     * 
     */
    public List<WorkbenchEventListType> getWorkbenchEvents() {
        if (workbenchEvents == null) {
            workbenchEvents = new ArrayList<WorkbenchEventListType>();
        }
        return this.workbenchEvents;
    }

}
